from simulations import *

S = Simulations(N_simulations = 5000, Frequencies=[0.01, 0.1, 1, 5, 10], dirname = "Amp5_test",mass = 1, L = 10, n_atoms = 1024, timestep = 0.001, time =10)
#S = Simulations(N_simulations = 4000, springConstants = [0.1, 1, 10, 100], dirname = "data2_m1_L10", mass = 1, L = 10, n_atoms = 1024, timestep = 0.001, time = 50)
#S = Simulations(N_simulations = 1, springConstants = ["infty",], dirname = "data2_m1_L10", mass = 1, L = 10, n_atoms = 1024, timestep = 0.001, time = 50)
#S = Simulations(N_simulations = 4000, springConstants = [0.1,1], dirname = "data_m1", mass = 1, L = 5, n_atoms = 1024, timestep = 0.001, time = 25)
#S = Simulations(N_simulations = 10, springConstants = [0.1], dirname = "data_dilute", mass = 1, L = 50, n_atoms = 1024, timestep = 0.001, time = 10)

S.create_filestructure()
S.create_configurations()
S.start_simulations()
S.calc_vacf("vacfz")
#S.calc_solvent_force_cf()
#S.remove_files_with_prefixes(["fy", "fz", "vely", "velz", "y", "z", "log"])
#S.write_input_file_without_ext_potential("test_1/configurations/1_k/traj0")
#print("# Input file written")
#S.start_simulations(extPot=False)
#print("# Simulations done")
#S.remove_files_with_prefixes(["no_ext_pot_fy", "no_ext_pot_fz", "no_ext_pot_vely", "no_ext_pot_velz", "no_ext_pot_y", "no_ext_pot_z", "log"])
#print("# Removing files done")
#S.calc_ff(10)
#print("# Fluctuating forces calculated")
#S.calc_term(10)
#print("# Term calculated")
